Spec lob location
DILCISBoard/SIARD pull request #65
Opened 2024-08-02 11:47 UTC by andersbonielsen

The specification for LOB location. Has beed added. 
README has been sligthly changed.

2024-08-05 10:33 UTC, mbangerter approved these changes

2024-09-04 08:37 UTC, ArneKristianGroven approved these changes

2024-09-04 10:01 UTC, karinbredenberg requested changes
Please change the filenames so it follows what has been decided upon for the specification itself. No spaces and no dots.

2024-09-27 14:08 UTC, andersbonielsen commented
> Please change the filenames so it follows what has been decided upon for the specification itself. No spaces and no dots.
Spaces in filename replaced with underscore
Dots in filename (before suffix) replaced with dashes

2024-10-28 11:56 UTC, andersbonielsen commented
The issues with this branch should be solved, so that commits can be merged.

2024-11-14 08:05 UTC, karinbredenberg approved these changes

2024-11-14 08:11 UTC, merged